server:
  port: 8082

spring:
  application:
    name: coffee-machine-service
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_machines_database
    username: postgres
    password: user

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

error-factory:
  code: "app"
  message: "app"