openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
  description: API для управления информацией о пользователях, домах и комнатах.

paths:
  /users:
    post:
      summary: Добавить нового пользователя при геристрации.
      security:
        - BearerAuth: [ ]
      tags:
        - User
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: Пользователь успешно добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /home:
    post:
      summary: Добавить дом.
      security:
        - BearerAuth: [ ]
      tags:
        - Home
      operationId: createHome
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Home'
      responses:
        '201':
          description: Дом успешно добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Home'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /home/{houseId}/invite:
    post:
      summary: Пригласить пользователя в дом.
      tags:
        - Houses
      operationId: inviteUserToHouse
      parameters:
        - in: path
          name: houseId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор дома.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: uuid
                  description: Уникальный идентификатор пользователя.
                role:
                  type: string
                  enum: [OWNER, GUEST]
                  description: Роль пользователя в доме.
      responses:
        '200':
          description: Пользователь успешно приглашён в дом.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/House'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /houses/{houseId}/rooms:
    post:
      summary: Добавить новую комнату в дом.
      tags:
        - Rooms
      operationId: createRoom
      parameters:
        - in: path
          name: houseId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор дома.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '201':
          description: Комната успешно создана.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор пользователя.
        name:
          type: string
          description: Имя пользователя.
        houses:
          type: array
          items:
            $ref: '#/components/schemas/House'
          description: Список домов, к которым принадлежит пользователь.

    House:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор дома.
        name:
          type: string
          description: Название дома.
        address:
          type: string
          description: Адрес дома.
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/Room'
          description: Список комнат в доме.

    Room:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор комнаты.
        name:
          type: string
          description: Название комнаты.

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки.
        message:
          type: string
          description: Сообщение об ошибке.