openapi: 3.0.3
info:
  title: Air Conditioner Service API
  version: 1.0.0
  description: API для управления кондиционерами в умных домах.

paths:
  /air-conditioners-info:
    post:
      summary: Добавить новый кондиционер.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: createAirConditionerInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInfo'
      responses:
        '201':
          description: Кондиционер успешно добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInfo'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-info/{airConditionerId}:
    get:
      summary: Получить информацию о кондиционере.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: getAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Информация о кондиционере.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInfo'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить информацию о кондиционере.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: updateAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInfo'
      responses:
        '200':
          description: Кондиционер успешно обновлён.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInfo'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удалить кондиционер.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: deleteAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '204':
          description: Кондиционер успешно удалён.
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-state:
    post:
      summary: Установить новое состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: createAirConditionerState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerState'
      responses:
        '201':
          description: Состояние кондиционера успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerState'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-state/{airConditionerId}:
    get:
      summary: Получить текущее состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: getAirConditionerState
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Текущее состояние кондиционера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerState'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить текущее состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: updateAirConditionerState
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerState'
      responses:
        '200':
          description: Состояние кондиционера успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerState'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-timer:
    post:
      summary: Установить новый таймер для кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerTimer
      operationId: createAirConditionerTimer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerTimer'
      responses:
        '201':
          description: Таймер кондиционера успешно установлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerTimer'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-timer/{airConditionerId}:
    get:
      summary: Получить информацию о таймере кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerTimer
      operationId: getAirConditionerTimer
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Информация о таймере кондиционера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerTimer'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить таймер кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerTimer
      operationId: updateAirConditionerTimer
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerTimer'
      responses:
        '200':
          description: Таймер кондиционера успешно обновлён.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerTimer'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удалить таймер кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerTimer
      operationId: deleteAirConditionerTimer
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '204':
          description: Таймер кондиционера успешно удалён.
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-maintenance:
    post:
      summary: Добавить новый график обслуживания кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerMaintenance
      operationId: createAirConditionerMaintenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerMaintenanceSchedule'
      responses:
        '201':
          description: График обслуживания кондиционера успешно добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerMaintenanceSchedule'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-maintenance/{airConditionerId}:
    get:
      summary: Получить график обслуживания кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerMaintenance
      operationId: getAirConditionerMaintenance
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Информация о графике обслуживания кондиционера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerMaintenanceSchedule'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить график обслуживания кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerMaintenance
      operationId: updateAirConditionerMaintenance
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerMaintenanceSchedule'
      responses:
        '200':
          description: График обслуживания кондиционера успешно обновлён.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerMaintenanceSchedule'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удалить график обслуживания кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerMaintenance
      operationId: deleteAirConditionerMaintenance
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '204':
          description: График обслуживания кондиционера успешно удалён.
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
components:
  schemas:
    AirConditionerState:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор записи о состоянии.
        airConditionerId:
          type: string
          format: uuid
          description: Идентификатор кондиционера, соответствующий его записи в AirConditionerInfo.
        mode:
          type: string
          enum: [COOLING, HEATING]
          description: Режим работы кондиционера (охлаждение или нагрев).
        temperature:
          type: integer
          minimum: 16
          maximum: 28
          description: Текущая установленная температура (от 16 до 28).
        fanSpeed:
          type: string
          enum: [LOW, MEDIUM, HIGH]
          description: Скорость обдува (низкая, средняя, высокая).
        status:
          type: string
          enum: [ON, OFF, STAND_BY]
          description: Текущий статус кондиционера.
        stateUpdatedAt:
          type: string
          format: date-time
          description: Временная метка последнего изменения состояния.

    AirConditionerInfo:
      type: object
      properties:
        airConditionerId:
          type: string
          format: uuid
          description: Уникальный идентификатор устройства.
        name:
          type: string
          description: Имя кондиционера (например, "Кондиционер в спальне").
        serialNumber:
          type: string
          description: Серийный номер кондиционера.
        manufacturer:
          type: string
          description: Производитель устройства (например, LG, Samsung).
        model:
          type: string
          description: Модель устройства.

    AirConditionerTimer:
      type: object
      properties:
        airConditionerId:
          type: string
          format: uuid
          description: Идентификатор устройства, для которого установлен таймер.
        startTime:
          type: string
          format: date-time
          description: Время включения кондиционера в серверной таймзоне.
        stopTime:
          type: string
          format: date-time
          nullable: true
          description: Время выключения кондиционера, если установлено (может быть null).
        recurrence:
          type: string
          enum: [DAILY, WEEKLY]
          description: Периодичность выполнения таймера (DAILY, WEEKLY, может быть null).

    AirConditionerMaintenanceSchedule:
      type: object
      properties:
        airConditionerId:
          type: string
          format: uuid
          description: Идентификатор кондиционера.
        nextMaintenanceDate:
          type: string
          format: date
          description: Дата следующего запланированного обслуживания.
        intervalDays:
          type: integer
          description: Периодичность обслуживания в днях.
        maintenanceStatus:
          type: string
          enum: [COMPLETED, POSTPONED, CANCELLED, SCHEDULED]
          description: Статус проведенного обслуживания (выполнено, перенесено, отменено, запланировано).

    Error:
      type: object
      properties:
        code:
          type: string
          description: Код ошибки.
        message:
          type: string
          description: Описание ошибки.