openapi: 3.0.3
info:
  title: Air Conditioner Service API
  version: 1.0.0
  description: API для управления кондиционерами в умных домах.

paths:
  /air-conditioners-info:
    post:
      summary: Добавить новый кондиционер.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: createAirConditionerInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInformation'
      responses:
        '201':
          description: Кондиционер успешно добавлен.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-info/{airConditionerId}:
    get:
      summary: Получить информацию о кондиционере.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: getAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Информация о кондиционере.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить информацию о кондиционере.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: updateAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInformation'
      responses:
        '200':
          description: Кондиционер успешно обновлён.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Удалить кондиционер.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerInfo
      operationId: deleteAirConditionerInfo
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '204':
          description: Кондиционер успешно удалён.
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-state:
    post:
      summary: Установить новое состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: createAirConditionerState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInformation'
      responses:
        '201':
          description: Состояние кондиционера успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /air-conditioners-state/{airConditionerId}:
    get:
      summary: Получить текущее состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: getAirConditionerState
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '200':
          description: Текущее состояние кондиционера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Обновить состояние кондиционера.
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: updateAirConditionerState
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirConditionerInformation'
      responses:
        '200':
          description: Состояние кондиционера успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirConditionerInformation'
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Удалить состояние кондиционера (при удалении кондиционера).
      security:
        - BearerAuth: [ ]
      tags:
        - AirConditionerState
      operationId: deleteAirConditionerState
      parameters:
        - in: path
          name: airConditionerId
          schema:
            type: string
            format: uuid
          required: true
          description: Уникальный идентификатор устройства кондиционера.
      responses:
        '204':
          description: Кондиционер успешно удалён.
        '400':
          description: Ошибка в данных запроса.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      
components:
  schemas:
    AirConditionerInformation:
      type: object
      properties:
        airConditionerId:
          type: string
          format: uuid
          description: Уникальный идентификатор устройства.
        name:
          type: string
          description: Имя кондиционера (например, "Кондиционер в спальне").
        serialNumber:
          type: string
          description: Серийный номер кондиционера.
        manufacturer:
          type: string
          description: Производитель устройства (например, LG, Samsung).
        model:
          type: string
          description: Модель устройства.
        mode:
          type: string
          enum: [ COOLING, HEATING ]
          description: Режим работы кондиционера (охлаждение или нагрев).
        temperature:
          type: integer
          minimum: 16
          maximum: 28
          description: Текущая установленная температура (от 16 до 28).
        fanSpeed:
          type: string
          enum: [ LOW, MEDIUM, HIGH ]
          description: Скорость обдува (низкая, средняя, высокая).
        status:
          type: string
          enum: [ ON, OFF ]
          description: Текущий статус кондиционера.
        stateUpdatedAt:
          type: string
          format: date-time
          description: Временная метка последнего изменения состояния.

    Error:
      type: object
      properties:
        code:
          type: string
          description: Код ошибки.
        message:
          type: string
          description: Описание ошибки.