server:
  port: 8081

spring:
  application:
    name: air-conditioner-service
  datasource:
    url: jdbc:postgresql://localhost:5432/air_conditioners_database
    username: postgres
    password: user

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#management:
  #endpoints:
    #web:
      #exposure:
        #include: health, info, metrics
  #metrics:
    #export:
      #prometheus:
        #enabled: true

error-factory:
  code: "app"
  message: "app"
